version: "3.9"

services:
  postgres:
    image: postgres:17
    env_file:
      - ./backend/.env.production
    ports:
      - "5435:5432"
    volumes:
      - postgres_production_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6381:6379"
    volumes:
      - redis_production_data:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: ./backend
    ports:
      - "5002:5000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - postgres
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${{ vars.VITE_API_URL_PROD }}
    ports:
      - "5175:80"
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend
    restart: always

volumes:
  postgres_production_data:
  redis_production_data:
