name: Deploy (Dev / Staging / Prod)

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_DIR: /home/kunalshah5301/ci-cd-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine environment & compose file
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "COMPOSE_FILE=docker-compose.dev.yml" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_DEV }}" >> $GITHUB_ENV

          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "COMPOSE_FILE=docker-compose.staging.yml" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_STAGING }}" >> $GITHUB_ENV

          else
            echo "COMPOSE_FILE=docker-compose.prod.yml" >> $GITHUB_ENV
            echo "VITE_API_URL=${{ vars.VITE_API_URL_PROD }}" >> $GITHUB_ENV
          fi
          
      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: .
          target: ${{ env.APP_DIR }}

      - name: Deploy on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.APP_DIR }}

            export VITE_API_URL="${{ env.VITE_API_URL }}"

            sudo docker compose \
              -f ${{ env.COMPOSE_FILE }} \
              -p ci-cd-docker-${GITHUB_REF_NAME} \
              up -d --build

            docker image prune -f
